USER_INPUT_VALIDATOR_NODE = "user_input_validator_node"
DB_CONFIG_VALIDATOR_NODE = "db_config_validator_node"
FETCH_DB_SCHEMA_NODE = "fetch_db_schema_node"
FORMAT_DB_SCHEMA_NODE = "format_db_schema_node"
SQL_GENERATION_NODE = "sql_generation_node"
DATA_FETCH_NODE = "data_fetch_node"
DATA_EXPLAINER_NODE = "data_explainer_node"
